title: "Pratyusa Kumar Tripathy"
tagline: "Quant | CFA | AI/ML | Risk Modeling"
description: >-
  Portfolio showcasing quantitative finance work, investment models, and AI-driven financial research.
url: "https://pratyusa-tripathy.github.io"
baseurl: ""
lang: "en"
theme_mode: "auto"

author:
  name: "Pratyusa Kumar Tripathy"
  avatar: "/assets/img/profile.jpg"
  bio: "Vice President @ JPMorgan | Quant Researcher | CFA L3 Cleared"
  location: "Mumbai, India"
  email: "pratyusa.tripathy@iiml.org"
  linkedin: "https://linkedin.com/in/pratyusatripathy"
  github: "https://github.com/pratyusa-tripathy"

footer:
  contact:
    - title: Email
      url: mailto:pratyusa.tripathy@iiml.org
    - title: LinkedIn
      url: https://linkedin.com/in/pratyusatripathy
